name: Publish docs to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Build schema references
        run: ./generateReferences.sh
      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      - name: Install deps
        run: yarn
      - name: Build docs
        run: yarn build --out-dir site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
